# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
env: flex
instance_class: F2

network:
  session_affinity: true
env_variables:
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 5MB
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 5MB

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65
